-- Migration to add AI-generated review tracking
-- Add columns to track whether a review is AI-generated

ALTER TABLE peer_assessment.peer_reviews 
ADD COLUMN is_ai_generated BOOLEAN DEFAULT false,
ADD COLUMN ai_model_used VARCHAR(50),
ADD COLUMN generated_by_instructor INTEGER REFERENCES peer_assessment.users(user_id);

-- Add comment for documentation
COMMENT ON COLUMN peer_assessment.peer_reviews.is_ai_generated IS 'Whether this review was generated by AI';
COMMENT ON COLUMN peer_assessment.peer_reviews.ai_model_used IS 'AI model used for generation (e.g., gpt-4, gpt-3.5-turbo)';
COMMENT ON COLUMN peer_assessment.peer_reviews.generated_by_instructor IS 'Instructor who generated the AI review';

-- Create index for AI reviews
CREATE INDEX idx_peer_reviews_ai_generated ON peer_assessment.peer_reviews(is_ai_generated);
